### ISSUE TITLE
Crash when click to highscore

### ISSUE THREAD

**Issue by ds2k5** [didier-v/breakable#2]
Hi,
if I click ob highscore in the menu the game crash.

![Screen Capture_select-area_20201209081325](https://user-images.githubusercontent.com/11292286/101597042-6db13480-39f6-11eb-84c0-0a54fc238561.png)

On the Console I can see this error:

ERROR: _load: Failed loading resource: res://hi_scores/hi_scores.tscn. Make sure resources have been imported by opening the project in the editor at least once.

the file is in the soruce code directory

```
$ find . -name hi_scores.tscn
./hi_scores/hi_scores.tscn

```

godot 3.2.3

![Screen Capture_select-area_20201209081235](https://user-images.githubusercontent.com/11292286/101596998-5d00be80-39f6-11eb-961c-b1c9da2179d8.png)

**Comment by didier-v** [comment]
Hi,

Sorry for not replying earlier.

This issue has been fixed in [this commit ](https://github.com/didier-v/breakable/commit/9c25fbe65771b64e0749e05df3eb17adc2b992f7).

Thank you for reporting it.
